### ISSUE TITLE
如何恢复修改过的网络配置

### ISSUE THREAD

**Issue by zhangoneone** [zuiwuchang/xray-webui#3]
请问这个程序关闭之后，有恢复改动过的网络配置吗？
或者需要怎么做才能恢复之前的网络配置

**Comment by zuiwuchang** [comment]
關閉時不會恢復網絡

當你啓動了透明代理後（只有在啓動透明代理時才會修改系統網絡設定），可以點擊網頁上的關閉透明代理(這會恢復網絡設置到啓動代理之前)

> 對於windows 你需要設置正確的網關地址，詳情請見項目 REAMDE.md
